var annotated_dup =
[
    [ "EP", "namespaceEP.html", [
      [ "U3D", "namespaceEP_1_1U3D.html", [
        [ "EDITOR", "namespaceEP_1_1U3D_1_1EDITOR.html", [
          [ "ARCH", "namespaceEP_1_1U3D_1_1EDITOR_1_1ARCH.html", [
            [ "BashArch", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BashArch.html", null ],
            [ "BuildAndroid", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildAndroid.html", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildAndroid" ],
            [ "BuildH5", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildH5.html", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildH5" ],
            [ "BuildiOS", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildiOS.html", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildiOS" ],
            [ "BuildWindows", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildWindows.html", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildWindows" ],
            [ "BuildWorker", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildWorker.html", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1BuildWorker" ],
            [ "WinArch", "classEP_1_1U3D_1_1EDITOR_1_1ARCH_1_1WinArch.html", null ]
          ] ],
          [ "ASSET", "namespaceEP_1_1U3D_1_1EDITOR_1_1ASSET.html", [
            [ "BuildAsset", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1BuildAsset.html", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1BuildAsset" ],
            [ "BuildTags", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1BuildTags.html", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1BuildTags" ],
            [ "ProcAudio", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcAudio.html", null ],
            [ "ProcLighting", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcLighting.html", null ],
            [ "ProcMissing", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcMissing.html", null ],
            [ "ProcModel", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcModel.html", null ],
            [ "ProcRefer", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcRefer.html", null ],
            [ "ProcRestore", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcRestore.html", null ],
            [ "ProcShader", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcShader.html", null ],
            [ "ProcSkip", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcSkip.html", null ],
            [ "ProcTexture", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcTexture.html", null ],
            [ "ProcUnicode", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcUnicode.html", null ],
            [ "ProcUseless", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcUseless.html", null ],
            [ "ProcVariant", "classEP_1_1U3D_1_1EDITOR_1_1ASSET_1_1ProcVariant.html", null ]
          ] ],
          [ "BASE", "namespaceEP_1_1U3D_1_1EDITOR_1_1BASE.html", [
            [ "Constants", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1Constants.html", null ],
            [ "EditorEvtcat", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1EditorEvtcat.html", null ],
            [ "EditorNet", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1EditorNet.html", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1EditorNet" ],
            [ "Helper", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1Helper.html", null ],
            [ "Loom", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1Loom.html", null ],
            [ "StaticOverrideAttribute", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1StaticOverrideAttribute.html", null ],
            [ "Window", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1Window.html", "classEP_1_1U3D_1_1EDITOR_1_1BASE_1_1Window" ]
          ] ],
          [ "EENG", "namespaceEP_1_1U3D_1_1EDITOR_1_1EENG.html", [
            [ "ENGPatch", "classEP_1_1U3D_1_1EDITOR_1_1EENG_1_1ENGPatch.html", null ]
          ] ],
          [ "EXCEL", "namespaceEP_1_1U3D_1_1EDITOR_1_1EXCEL.html", [
            [ "BuildExcel", "classEP_1_1U3D_1_1EDITOR_1_1EXCEL_1_1BuildExcel.html", "classEP_1_1U3D_1_1EDITOR_1_1EXCEL_1_1BuildExcel" ]
          ] ],
          [ "ILR", "namespaceEP_1_1U3D_1_1EDITOR_1_1ILR.html", [
            [ "BuildILR", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1BuildILR.html", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1BuildILR" ],
            [ "ILREditor", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1ILREditor.html", null ],
            [ "MenuILR", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1MenuILR.html", null ],
            [ "ProcILR", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1ProcILR.html", null ],
            [ "ProcNewILR", "classEP_1_1U3D_1_1EDITOR_1_1ILR_1_1ProcNewILR.html", null ]
          ] ]
        ] ],
        [ "LIBRARY", "namespaceEP_1_1U3D_1_1LIBRARY.html", [
          [ "ASSET", "namespaceEP_1_1U3D_1_1LIBRARY_1_1ASSET.html", [
            [ "AssetManager", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1AssetManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1AssetManager" ],
            [ "FileManifest", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1FileManifest.html", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1FileManifest" ],
            [ "ObjectRefer", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1ObjectRefer.html", "classEP_1_1U3D_1_1LIBRARY_1_1ASSET_1_1ObjectRefer" ]
          ] ],
          [ "AUDIO", "namespaceEP_1_1U3D_1_1LIBRARY_1_1AUDIO.html", [
            [ "AudioManager", "classEP_1_1U3D_1_1LIBRARY_1_1AUDIO_1_1AudioManager.html", null ]
          ] ],
          [ "BASE", "namespaceEP_1_1U3D_1_1LIBRARY_1_1BASE.html", [
            [ "Constants", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Constants.html", null ],
            [ "Helper", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Helper.html", null ],
            [ "Loom", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Loom.html", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Loom" ],
            [ "Platform", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Platform.html", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Platform" ],
            [ "PlatformAttribute", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1PlatformAttribute.html", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1PlatformAttribute" ],
            [ "Preferences", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Preferences.html", "classEP_1_1U3D_1_1LIBRARY_1_1BASE_1_1Preferences" ]
          ] ],
          [ "EVT", "namespaceEP_1_1U3D_1_1LIBRARY_1_1EVT.html", [
            [ "Evt", "classEP_1_1U3D_1_1LIBRARY_1_1EVT_1_1Evt.html", "classEP_1_1U3D_1_1LIBRARY_1_1EVT_1_1Evt" ],
            [ "EvtManager", "classEP_1_1U3D_1_1LIBRARY_1_1EVT_1_1EvtManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1EVT_1_1EvtManager" ]
          ] ],
          [ "NET", "namespaceEP_1_1U3D_1_1LIBRARY_1_1NET.html", [
            [ "HttpListener", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1HttpListener.html", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1HttpListener" ],
            [ "NetConnection", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1NetConnection.html", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1NetConnection" ],
            [ "NetManager", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1NetManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1NetManager" ],
            [ "NetPacket", "classEP_1_1U3D_1_1LIBRARY_1_1NET_1_1NetPacket.html", null ]
          ] ],
          [ "PATCH", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PATCH.html", [
            [ "Patcher", "classEP_1_1U3D_1_1LIBRARY_1_1PATCH_1_1Patcher.html", "classEP_1_1U3D_1_1LIBRARY_1_1PATCH_1_1Patcher" ],
            [ "Updater", "classEP_1_1U3D_1_1LIBRARY_1_1PATCH_1_1Updater.html", "classEP_1_1U3D_1_1LIBRARY_1_1PATCH_1_1Updater" ]
          ] ],
          [ "PCHAT", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PCHAT.html", [
            [ "AuthenticationValues", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1AuthenticationValues.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1AuthenticationValues" ],
            [ "ChannelCreationOptions", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChannelCreationOptions.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChannelCreationOptions" ],
            [ "ChannelWellKnownProperties", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChannelWellKnownProperties.html", null ],
            [ "ChatAppSettings", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatAppSettings.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatAppSettings" ],
            [ "ChatChannel", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatChannel.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatChannel" ],
            [ "ChatClient", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatClient.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatClient" ],
            [ "ChatEventCode", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatEventCode.html", null ],
            [ "ChatOperationCode", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatOperationCode.html", null ],
            [ "ChatParameterCode", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatParameterCode.html", null ],
            [ "ChatPeer", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatPeer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ChatPeer" ],
            [ "ErrorCode", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ErrorCode.html", null ],
            [ "IChatClientListener", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1IChatClientListener.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1IChatClientListener" ],
            [ "ParameterCode", "classEP_1_1U3D_1_1LIBRARY_1_1PCHAT_1_1ParameterCode.html", null ]
          ] ],
          [ "PNET", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PNET.html", [
            [ "ActorProperties", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ActorProperties.html", null ],
            [ "AppSettings", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1AppSettings.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1AppSettings" ],
            [ "AuthenticationValues", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1AuthenticationValues.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1AuthenticationValues" ],
            [ "ConnectionCallbacksContainer", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ConnectionCallbacksContainer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ConnectionCallbacksContainer" ],
            [ "ConnectionHandler", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ConnectionHandler.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ConnectionHandler" ],
            [ "EnterRoomParams", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1EnterRoomParams.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1EnterRoomParams" ],
            [ "ErrorCode", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ErrorCode.html", null ],
            [ "ErrorInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ErrorInfo.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ErrorInfo" ],
            [ "EventCode", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1EventCode.html", null ],
            [ "FindFriendsOptions", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1FindFriendsOptions.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1FindFriendsOptions" ],
            [ "FriendInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1FriendInfo.html", null ],
            [ "GamePropertyKey", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1GamePropertyKey.html", null ],
            [ "IConnectionCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IConnectionCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IConnectionCallbacks" ],
            [ "IErrorInfoCallback", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IErrorInfoCallback.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IErrorInfoCallback" ],
            [ "IInRoomCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IInRoomCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IInRoomCallbacks" ],
            [ "ILobbyCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ILobbyCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ILobbyCallbacks" ],
            [ "IMatchmakingCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IMatchmakingCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IMatchmakingCallbacks" ],
            [ "IOnEventCallback", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IOnEventCallback.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IOnEventCallback" ],
            [ "IWebRpcCallback", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IWebRpcCallback.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1IWebRpcCallback" ],
            [ "LoadBalancingClient", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1LoadBalancingClient.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1LoadBalancingClient" ],
            [ "LoadBalancingPeer", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1LoadBalancingPeer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1LoadBalancingPeer" ],
            [ "MatchMakingCallbacksContainer", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1MatchMakingCallbacksContainer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1MatchMakingCallbacksContainer" ],
            [ "OperationCode", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1OperationCode.html", null ],
            [ "OpJoinRandomRoomParams", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1OpJoinRandomRoomParams.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1OpJoinRandomRoomParams" ],
            [ "ParameterCode", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1ParameterCode.html", null ],
            [ "PhotonAppSettings", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PhotonAppSettings.html", null ],
            [ "PhotonPing", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PhotonPing.html", null ],
            [ "PhotonPortDefinition", "structEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PhotonPortDefinition.html", "structEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PhotonPortDefinition" ],
            [ "PingMono", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PingMono.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1PingMono" ],
            [ "Player", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Player.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Player" ],
            [ "RaiseEventOptions", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RaiseEventOptions.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RaiseEventOptions" ],
            [ "Region", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Region.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Region" ],
            [ "RegionHandler", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RegionHandler.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RegionHandler" ],
            [ "RegionPinger", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RegionPinger.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RegionPinger" ],
            [ "Room", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Room.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1Room" ],
            [ "RoomInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RoomInfo.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RoomInfo" ],
            [ "RoomOptions", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RoomOptions.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1RoomOptions" ],
            [ "SupportLogger", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1SupportLogger.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1SupportLogger" ],
            [ "TypedLobby", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1TypedLobby.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1TypedLobby" ],
            [ "TypedLobbyInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1TypedLobbyInfo.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1TypedLobbyInfo" ],
            [ "WebFlags", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1WebFlags.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1WebFlags" ],
            [ "WebRpcResponse", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1WebRpcResponse.html", "classEP_1_1U3D_1_1LIBRARY_1_1PNET_1_1WebRpcResponse" ]
          ] ],
          [ "POOL", "namespaceEP_1_1U3D_1_1LIBRARY_1_1POOL.html", [
            [ "GameObjectPool", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1GameObjectPool.html", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1GameObjectPool" ],
            [ "ObjectPool", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1ObjectPool.html", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1ObjectPool" ],
            [ "StreamBuffer", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1StreamBuffer.html", "classEP_1_1U3D_1_1LIBRARY_1_1POOL_1_1StreamBuffer" ]
          ] ],
          [ "PPUN", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PPUN.html", [
            [ "ButtonInsideScrollList", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ButtonInsideScrollList.html", null ],
            [ "ByteComparer", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ByteComparer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ByteComparer" ],
            [ "CellTree", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CellTree.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CellTree" ],
            [ "CellTreeNode", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CellTreeNode.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CellTreeNode" ],
            [ "ConnectAndJoinRandom", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ConnectAndJoinRandom.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ConnectAndJoinRandom" ],
            [ "CountdownTimer", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CountdownTimer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CountdownTimer" ],
            [ "CullArea", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CullArea.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CullArea" ],
            [ "CullingHandler", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CullingHandler.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1CullingHandler" ],
            [ "DefaultPool", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1DefaultPool.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1DefaultPool" ],
            [ "EventSystemSpawner", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1EventSystemSpawner.html", null ],
            [ "GraphicToggleIsOnTransition", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1GraphicToggleIsOnTransition.html", null ],
            [ "InstantiateParameters", "structEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1InstantiateParameters.html", null ],
            [ "IOnPhotonViewControllerChange", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewControllerChange.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewControllerChange" ],
            [ "IOnPhotonViewOwnerChange", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewOwnerChange.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewOwnerChange" ],
            [ "IOnPhotonViewPreNetDestroy", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewPreNetDestroy.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IOnPhotonViewPreNetDestroy" ],
            [ "IPhotonViewCallback", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPhotonViewCallback.html", null ],
            [ "IPunInstantiateMagicCallback", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunInstantiateMagicCallback.html", null ],
            [ "IPunObservable", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunObservable.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunObservable" ],
            [ "IPunOwnershipCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunOwnershipCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunOwnershipCallbacks" ],
            [ "IPunPrefabPool", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunPrefabPool.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunPrefabPool" ],
            [ "IPunTurnManagerCallbacks", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunTurnManagerCallbacks.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1IPunTurnManagerCallbacks" ],
            [ "MonoBehaviourPun", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1MonoBehaviourPun.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1MonoBehaviourPun" ],
            [ "MonoBehaviourPunCallbacks", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1MonoBehaviourPunCallbacks.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1MonoBehaviourPunCallbacks" ],
            [ "MoveByKeys", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1MoveByKeys.html", null ],
            [ "OnClickDestroy", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnClickDestroy.html", null ],
            [ "OnClickInstantiate", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnClickInstantiate.html", null ],
            [ "OnClickRpc", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnClickRpc.html", null ],
            [ "OnEscapeQuit", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnEscapeQuit.html", null ],
            [ "OnJoinedInstantiate", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnJoinedInstantiate.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnJoinedInstantiate" ],
            [ "OnPointerOverTooltip", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnPointerOverTooltip.html", null ],
            [ "OnStartDelete", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1OnStartDelete.html", null ],
            [ "PhotonAnimatorView", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonAnimatorView.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonAnimatorView" ],
            [ "PhotonHandler", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonHandler.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonHandler" ],
            [ "PhotonLagSimulationGui", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonLagSimulationGui.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonLagSimulationGui" ],
            [ "PhotonMessageInfo", "structEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonMessageInfo.html", "structEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonMessageInfo" ],
            [ "PhotonRigidbody2DView", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonRigidbody2DView.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonRigidbody2DView" ],
            [ "PhotonRigidbodyView", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonRigidbodyView.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonRigidbodyView" ],
            [ "PhotonStatsGui", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStatsGui.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStatsGui" ],
            [ "PhotonStream", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStream.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStream" ],
            [ "PhotonStreamQueue", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStreamQueue.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonStreamQueue" ],
            [ "PhotonTeam", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTeam.html", null ],
            [ "PhotonTeamsManager", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTeamsManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTeamsManager" ],
            [ "PhotonTransformView", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformView.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformView" ],
            [ "PhotonTransformViewClassic", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewClassic.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewClassic" ],
            [ "PhotonTransformViewPositionControl", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewPositionControl.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewPositionControl" ],
            [ "PhotonTransformViewPositionModel", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewPositionModel.html", null ],
            [ "PhotonTransformViewRotationControl", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewRotationControl.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewRotationControl" ],
            [ "PhotonTransformViewRotationModel", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewRotationModel.html", null ],
            [ "PhotonTransformViewScaleControl", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewScaleControl.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewScaleControl" ],
            [ "PhotonTransformViewScaleModel", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonTransformViewScaleModel.html", null ],
            [ "PhotonView", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonView.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PhotonView" ],
            [ "PlayerNumbering", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PlayerNumbering.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PlayerNumbering" ],
            [ "PointedAtGameObjectInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PointedAtGameObjectInfo.html", null ],
            [ "PunPlayerScores", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunPlayerScores.html", null ],
            [ "PunRPC", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunRPC.html", null ],
            [ "PunTeams", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunTeams.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunTeams" ],
            [ "PunTurnManager", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunTurnManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1PunTurnManager" ],
            [ "SceneManagerHelper", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1SceneManagerHelper.html", null ],
            [ "ServerSettings", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ServerSettings.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1ServerSettings" ],
            [ "SmoothSyncMovement", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1SmoothSyncMovement.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1SmoothSyncMovement" ],
            [ "StatesGui", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1StatesGui.html", null ],
            [ "TabViewManager", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TabViewManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TabViewManager" ],
            [ "TextButtonTransition", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TextButtonTransition.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TextButtonTransition" ],
            [ "TextToggleIsOnTransition", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TextToggleIsOnTransition.html", "classEP_1_1U3D_1_1LIBRARY_1_1PPUN_1_1TextToggleIsOnTransition" ]
          ] ],
          [ "PROTO", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PROTO.html", [
            [ "IProto", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PROTO_1_1IProto.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PROTO_1_1IProto" ],
            [ "ProtoDecoder", "classEP_1_1U3D_1_1LIBRARY_1_1PROTO_1_1ProtoDecoder.html", null ],
            [ "ProtoEncoder", "classEP_1_1U3D_1_1LIBRARY_1_1PROTO_1_1ProtoEncoder.html", null ]
          ] ],
          [ "PVOICE", "namespaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE.html", [
            [ "AndroidAudioInAEC", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AndroidAudioInAEC.html", null ],
            [ "AndroidAudioInParameters", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AndroidAudioInParameters.html", null ],
            [ "AudioChangesHandler", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioChangesHandler.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioChangesHandler" ],
            [ "AudioClipWrapper", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioClipWrapper.html", null ],
            [ "AudioDesc", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioDesc.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioDesc" ],
            [ "AudioInChangeNotifierNotSupported", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioInChangeNotifierNotSupported.html", null ],
            [ "AudioInEnumeratorUnity", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioInEnumeratorUnity.html", null ],
            [ "AudioOutCapture", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioOutCapture.html", null ],
            [ "AudioOutDelayControl", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioOutDelayControl.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioOutDelayControl" ],
            [ "AudioOutDummy", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioOutDummy.html", null ],
            [ "AudioSessionParameters", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioSessionParameters.html", null ],
            [ "AudioSyncBuffer", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1AudioSyncBuffer.html", null ],
            [ "BufferReaderPushAdapter", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapter.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapter" ],
            [ "BufferReaderPushAdapterAsyncPool", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPool.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPool" ],
            [ "BufferReaderPushAdapterAsyncPoolCopy", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolCopy.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolCopy" ],
            [ "BufferReaderPushAdapterAsyncPoolFloatToShort", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolFloatToShort.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolFloatToShort" ],
            [ "BufferReaderPushAdapterAsyncPoolShortToFloat", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolShortToFloat.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterAsyncPoolShortToFloat" ],
            [ "BufferReaderPushAdapterBase", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterBase.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1BufferReaderPushAdapterBase" ],
            [ "ConnectAndJoin", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ConnectAndJoin.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ConnectAndJoin" ],
            [ "DeviceEnumeratorBase", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1DeviceEnumeratorBase.html", null ],
            [ "DeviceFeatures", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1DeviceFeatures.html", null ],
            [ "DeviceInfo", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1DeviceInfo.html", null ],
            [ "FactoryPrimitiveArrayPool", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1FactoryPrimitiveArrayPool.html", null ],
            [ "FactoryReusableArray", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1FactoryReusableArray.html", null ],
            [ "Flip", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Flip.html", null ],
            [ "FrameBuffer", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1FrameBuffer.html", null ],
            [ "FrameOut", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1FrameOut.html", null ],
            [ "Framer", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Framer.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Framer" ],
            [ "IAudioDesc", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioDesc.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioDesc" ],
            [ "IAudioInChangeNotifier", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioInChangeNotifier.html", null ],
            [ "IAudioOut", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioOut.html", null ],
            [ "IAudioPusher", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioPusher.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioPusher" ],
            [ "IAudioReader", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IAudioReader.html", null ],
            [ "IDataReader", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDataReader.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDataReader" ],
            [ "IDecoder", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDecoder.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDecoder" ],
            [ "IDecoderDirect", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDecoderDirect.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDecoderDirect" ],
            [ "IDeviceEnumerator", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IDeviceEnumerator.html", null ],
            [ "IEncoder", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoder.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoder" ],
            [ "IEncoderDirect", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoderDirect.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoderDirect" ],
            [ "IEncoderDirectImage", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoderDirectImage.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IEncoderDirectImage" ],
            [ "ILocalVoiceAudio", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ILocalVoiceAudio.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ILocalVoiceAudio" ],
            [ "ILogger", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ILogger.html", null ],
            [ "ImageBufferInfo", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferInfo.html", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferInfo" ],
            [ "ImageBufferNative", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferNative.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferNative" ],
            [ "ImageBufferNativeAlloc", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferNativeAlloc.html", null ],
            [ "ImageBufferNativeGCHandleSinglePlane", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferNativeGCHandleSinglePlane.html", null ],
            [ "ImageBufferNativePool", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ImageBufferNativePool.html", null ],
            [ "IProcessor", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IProcessor.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IProcessor" ],
            [ "IResettable", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IResettable.html", null ],
            [ "IServiceable", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IServiceable.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IServiceable" ],
            [ "IVoiceTransport", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1IVoiceTransport.html", null ],
            [ "LoadBalancingTransport", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LoadBalancingTransport.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LoadBalancingTransport" ],
            [ "LoadBalancingTransport2", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LoadBalancingTransport2.html", null ],
            [ "LocalVoice", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoice.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoice" ],
            [ "LocalVoiceAudio", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudio.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudio" ],
            [ "LocalVoiceAudioDummy", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudioDummy.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudioDummy" ],
            [ "LocalVoiceAudioFloat", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudioFloat.html", null ],
            [ "LocalVoiceAudioShort", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceAudioShort.html", null ],
            [ "LocalVoiceFramed", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceFramed.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceFramed" ],
            [ "LocalVoiceFramedBase", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceFramedBase.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1LocalVoiceFramedBase" ],
            [ "Logger", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Logger.html", null ],
            [ "MicAmplifier", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicAmplifier.html", null ],
            [ "MicAmplifierFloat", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicAmplifierFloat.html", null ],
            [ "MicAmplifierShort", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicAmplifierShort.html", null ],
            [ "MicrophonePermission", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicrophonePermission.html", null ],
            [ "MicWrapper", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicWrapper.html", null ],
            [ "MicWrapperPusher", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicWrapperPusher.html", null ],
            [ "MicWrapperPusherOnAudioFilterRead", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1MicWrapperPusherOnAudioFilterRead.html", null ],
            [ "ObjectFactory", "interfaceEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ObjectFactory.html", null ],
            [ "ObjectPool", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ObjectPool.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1ObjectPool" ],
            [ "OpusCodec", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusCodec.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusCodec" ],
            [ "OpusDecoder", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusDecoder.html", null ],
            [ "OpusDecoderAsync", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusDecoderAsync.html", null ],
            [ "OpusEncoder", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusEncoder.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusEncoder" ],
            [ "OpusException", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1OpusException.html", null ],
            [ "PhotonAppSettings", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PhotonAppSettings.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PhotonAppSettings" ],
            [ "PhotonVoiceCreatedParams", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PhotonVoiceCreatedParams.html", null ],
            [ "PhotonVoiceLagSimulationGui", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PhotonVoiceLagSimulationGui.html", null ],
            [ "PhotonVoiceStatsGui", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PhotonVoiceStatsGui.html", null ],
            [ "PrimitiveArrayPool", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1PrimitiveArrayPool.html", null ],
            [ "RawCodec", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RawCodec.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RawCodec" ],
            [ "Recorder", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Recorder.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Recorder" ],
            [ "RecorderPreset", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RecorderPreset.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RecorderPreset" ],
            [ "RemoteVoiceInfo", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RemoteVoiceInfo.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RemoteVoiceInfo" ],
            [ "RemoteVoiceLink", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RemoteVoiceLink.html", null ],
            [ "RemoteVoiceOptions", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RemoteVoiceOptions.html", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1RemoteVoiceOptions" ],
            [ "SaveIncomingStreamToFile", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1SaveIncomingStreamToFile.html", null ],
            [ "SaveOutgoingStreamToFile", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1SaveOutgoingStreamToFile.html", null ],
            [ "Speaker", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Speaker.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1Speaker" ],
            [ "SpeakerAudioFilterRead", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1SpeakerAudioFilterRead.html", null ],
            [ "TestTone", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1TestTone.html", null ],
            [ "UnityAudioOut", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnityAudioOut.html", null ],
            [ "UnityVoiceClient", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnityVoiceClient.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnityVoiceClient" ],
            [ "UnsupportedCodecException", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedCodecException.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedCodecException" ],
            [ "UnsupportedPlatformException", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedPlatformException.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedPlatformException" ],
            [ "UnsupportedSampleTypeException", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedSampleTypeException.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1UnsupportedSampleTypeException" ],
            [ "VoiceClient", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceClient.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceClient" ],
            [ "VoiceComponent", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceComponent.html", null ],
            [ "VoiceComponentImpl", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceComponentImpl.html", null ],
            [ "VoiceConnection", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceConnection.html", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceConnection" ],
            [ "VoiceEvent", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceEvent.html", null ],
            [ "VoiceInfo", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceInfo.html", "structEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceInfo" ],
            [ "VoiceLogger", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1VoiceLogger.html", null ],
            [ "WaveWriter", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1WaveWriter.html", null ],
            [ "WebRtcAudioDsp", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1WebRtcAudioDsp.html", null ],
            [ "WebRTCAudioLib", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1WebRTCAudioLib.html", null ],
            [ "WebRTCAudioProcessor", "classEP_1_1U3D_1_1LIBRARY_1_1PVOICE_1_1WebRTCAudioProcessor.html", null ]
          ] ],
          [ "REPORT", "namespaceEP_1_1U3D_1_1LIBRARY_1_1REPORT.html", [
            [ "Reporter", "classEP_1_1U3D_1_1LIBRARY_1_1REPORT_1_1Reporter.html", "classEP_1_1U3D_1_1LIBRARY_1_1REPORT_1_1Reporter" ]
          ] ],
          [ "SCENE", "namespaceEP_1_1U3D_1_1LIBRARY_1_1SCENE.html", [
            [ "IScene", "interfaceEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1IScene.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1IScene" ],
            [ "Scene", "classEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1Scene.html", "classEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1Scene" ],
            [ "SceneManager", "classEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1SceneManager.html", "classEP_1_1U3D_1_1LIBRARY_1_1SCENE_1_1SceneManager" ]
          ] ],
          [ "UI", "namespaceEP_1_1U3D_1_1LIBRARY_1_1UI.html", [
            [ "CollisionEnterWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1CollisionEnterWrap.html", null ],
            [ "CollisionExitWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1CollisionExitWrap.html", null ],
            [ "CollisionStayWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1CollisionStayWrap.html", null ],
            [ "IUIWindow", "interfaceEP_1_1U3D_1_1LIBRARY_1_1UI_1_1IUIWindow.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1UI_1_1IUIWindow" ],
            [ "TriggerEnterWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1TriggerEnterWrap.html", null ],
            [ "TriggerExitWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1TriggerExitWrap.html", null ],
            [ "TriggerStayWrap", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1TriggerStayWrap.html", null ],
            [ "UIButtonScale", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIButtonScale.html", null ],
            [ "UICameraMask", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UICameraMask.html", null ],
            [ "UIColliderListener", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIColliderListener.html", null ],
            [ "UIEventListener", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIEventListener.html", null ],
            [ "UIHelper", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIHelper.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIHelper" ],
            [ "UIIndex", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIIndex.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIIndex" ],
            [ "UIManager", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIManager.html", null ],
            [ "UIMeta", "interfaceEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIMeta.html", "interfaceEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIMeta" ],
            [ "UIPinCamera", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIPinCamera.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIPinCamera" ],
            [ "UIPinTarget", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIPinTarget.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIPinTarget" ],
            [ "UIRoundRawImage", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIRoundRawImage.html", null ],
            [ "UISound", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UISound.html", null ],
            [ "UISpriteAnim", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UISpriteAnim.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UISpriteAnim" ],
            [ "UIWindow", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIWindow.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIWindow" ],
            [ "UIWrapContent", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIWrapContent.html", "classEP_1_1U3D_1_1LIBRARY_1_1UI_1_1UIWrapContent" ]
          ] ]
        ] ],
        [ "RUNTIME", "namespaceEP_1_1U3D_1_1RUNTIME.html", [
          [ "ILR", "namespaceEP_1_1U3D_1_1RUNTIME_1_1ILR.html", [
            [ "JSON", "namespaceEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1JSON.html", [
              [ "JsonMapper", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1JSON_1_1JsonMapper.html", null ]
            ] ],
            [ "NET", "namespaceEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1NET.html", [
              [ "NetManager", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1NET_1_1NetManager.html", null ]
            ] ],
            [ "UI", "namespaceEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1UI.html", [
              [ "UIHelper", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1UI_1_1UIHelper.html", null ],
              [ "UIManager", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1UI_1_1UIManager.html", null ],
              [ "UIWindow", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1UI_1_1UIWindow.html", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1UI_1_1UIWindow" ]
            ] ],
            [ "ILRComponent", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1ILRComponent.html", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1ILRComponent" ],
            [ "ILRManager", "classEP_1_1U3D_1_1RUNTIME_1_1ILR_1_1ILRManager.html", null ]
          ] ],
          [ "LUA", "namespaceEP_1_1U3D_1_1RUNTIME_1_1LUA.html", [
            [ "BASE", "namespaceEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1BASE.html", [
              [ "Helper", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1BASE_1_1Helper.html", null ]
            ] ],
            [ "SCENE", "namespaceEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1SCENE.html", [
              [ "Scene", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1SCENE_1_1Scene.html", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1SCENE_1_1Scene" ]
            ] ],
            [ "UI", "namespaceEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1UI.html", [
              [ "UIHelper", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1UI_1_1UIHelper.html", null ],
              [ "UIManager", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1UI_1_1UIManager.html", null ],
              [ "UIMeta", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1UI_1_1UIMeta.html", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1UI_1_1UIMeta" ]
            ] ],
            [ "LuaComponent", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaComponent.html", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaComponent" ],
            [ "LuaDebugTool", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaDebugTool.html", null ],
            [ "LuaLoader", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaLoader.html", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaLoader" ],
            [ "LuaManager", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaManager.html", null ],
            [ "LuaValueInfo", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaValueInfo.html", "classEP_1_1U3D_1_1RUNTIME_1_1LUA_1_1LuaValueInfo" ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "ExitGames", "namespaceExitGames.html", [
      [ "Demos", "namespaceExitGames_1_1Demos.html", [
        [ "DemoPunVoice", "namespaceExitGames_1_1Demos_1_1DemoPunVoice.html", [
          [ "BaseController", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1BaseController.html", null ],
          [ "BetterToggle", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1BetterToggle.html", null ],
          [ "ChangePOV", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1ChangePOV.html", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1ChangePOV" ],
          [ "CharacterInstantiation", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1CharacterInstantiation.html", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1CharacterInstantiation" ],
          [ "FirstPersonController", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1FirstPersonController.html", null ],
          [ "OrthographicController", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1OrthographicController.html", null ],
          [ "ThirdPersonController", "classExitGames_1_1Demos_1_1DemoPunVoice_1_1ThirdPersonController.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Photon", "namespacePhoton.html", [
      [ "Voice", "namespacePhoton_1_1Voice.html", [
        [ "Fusion", "namespacePhoton_1_1Voice_1_1Fusion.html", [
          [ "Editor", "namespacePhoton_1_1Voice_1_1Fusion_1_1Editor.html", [
            [ "VoiceEditorHelper", "classPhoton_1_1Voice_1_1Fusion_1_1Editor_1_1VoiceEditorHelper.html", null ]
          ] ]
        ] ],
        [ "Unity", "namespacePhoton_1_1Voice_1_1Unity.html", [
          [ "Demos", "namespacePhoton_1_1Voice_1_1Unity_1_1Demos.html", [
            [ "DemoVoiceUI", "namespacePhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI.html", [
              [ "CodecSettingsUI", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI_1_1CodecSettingsUI.html", null ],
              [ "DemoVoiceUI", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI_1_1DemoVoiceUI.html", null ],
              [ "MicRef", "structPhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI_1_1MicRef.html", null ],
              [ "MicrophoneDropdownFiller", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI_1_1MicrophoneDropdownFiller.html", null ],
              [ "RemoteSpeakerUI", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1DemoVoiceUI_1_1RemoteSpeakerUI.html", null ]
            ] ],
            [ "BackgroundMusicController", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1BackgroundMusicController.html", null ],
            [ "SidebarToggle", "classPhoton_1_1Voice_1_1Unity_1_1Demos_1_1SidebarToggle.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "UnityStandardAssets", "namespaceUnityStandardAssets.html", [
      [ "CrossPlatformInput", "namespaceUnityStandardAssets_1_1CrossPlatformInput.html", [
        [ "PlatformSpecific", "namespaceUnityStandardAssets_1_1CrossPlatformInput_1_1PlatformSpecific.html", [
          [ "MobileInput", "classUnityStandardAssets_1_1CrossPlatformInput_1_1PlatformSpecific_1_1MobileInput.html", null ],
          [ "StandaloneInput", "classUnityStandardAssets_1_1CrossPlatformInput_1_1PlatformSpecific_1_1StandaloneInput.html", null ]
        ] ],
        [ "AxisTouchButton", "classUnityStandardAssets_1_1CrossPlatformInput_1_1AxisTouchButton.html", null ],
        [ "ButtonHandler", "classUnityStandardAssets_1_1CrossPlatformInput_1_1ButtonHandler.html", null ],
        [ "InputAxisScrollbar", "classUnityStandardAssets_1_1CrossPlatformInput_1_1InputAxisScrollbar.html", null ],
        [ "Joystick", "classUnityStandardAssets_1_1CrossPlatformInput_1_1Joystick.html", null ],
        [ "MobileControlRig", "classUnityStandardAssets_1_1CrossPlatformInput_1_1MobileControlRig.html", null ],
        [ "TouchPad", "classUnityStandardAssets_1_1CrossPlatformInput_1_1TouchPad.html", null ],
        [ "VirtualInput", "classUnityStandardAssets_1_1CrossPlatformInput_1_1VirtualInput.html", null ]
      ] ]
    ] ],
    [ "ActiveAnimation", "classActiveAnimation.html", "classActiveAnimation" ],
    [ "ActiveAnimationEditor", "classActiveAnimationEditor.html", null ],
    [ "AnimatedAlpha", "classAnimatedAlpha.html", null ],
    [ "AnimatedColor", "classAnimatedColor.html", null ],
    [ "AnimatedWidget", "classAnimatedWidget.html", null ],
    [ "BetterList", "classBetterList.html", "classBetterList" ],
    [ "BMFont", "classBMFont.html", "classBMFont" ],
    [ "BMGlyph", "classBMGlyph.html", "classBMGlyph" ],
    [ "BMSymbol", "classBMSymbol.html", "classBMSymbol" ],
    [ "ByteReader", "classByteReader.html", "classByteReader" ],
    [ "ChangeColor", "classChangeColor.html", null ],
    [ "ChangeName", "classChangeName.html", null ],
    [ "ComponentSelector", "classComponentSelector.html", null ],
    [ "DoNotObfuscateNGUI", "classDoNotObfuscateNGUI.html", null ],
    [ "EnvelopContent", "classEnvelopContent.html", null ],
    [ "EventDelegate", "classEventDelegate.html", "classEventDelegate" ],
    [ "EventDelegateDrawer", "classEventDelegateDrawer.html", null ],
    [ "ExcelReader", "classExcelReader.html", null ],
    [ "INGUIAtlas", "interfaceINGUIAtlas.html", "interfaceINGUIAtlas" ],
    [ "INGUIFont", "interfaceINGUIFont.html", "interfaceINGUIFont" ],
    [ "INGUITextureProcessor", "interfaceINGUITextureProcessor.html", null ],
    [ "LanguageSelection", "classLanguageSelection.html", "classLanguageSelection" ],
    [ "MinMaxRangeAttribute", "classMinMaxRangeAttribute.html", null ],
    [ "MinMaxRangeAttributeDrawer", "classMinMaxRangeAttributeDrawer.html", null ],
    [ "MouseLookHelper", "classMouseLookHelper.html", null ],
    [ "NGUIAtlas", "classNGUIAtlas.html", "classNGUIAtlas" ],
    [ "NGUIAtlasInspector", "classNGUIAtlasInspector.html", "classNGUIAtlasInspector" ],
    [ "NGUIDebug", "classNGUIDebug.html", null ],
    [ "NGUIFont", "classNGUIFont.html", "classNGUIFont" ],
    [ "NGUIFontInspector", "classNGUIFontInspector.html", "classNGUIFontInspector" ],
    [ "NGUIJson", "classNGUIJson.html", null ],
    [ "NGUISelectionTools", "classNGUISelectionTools.html", null ],
    [ "NGUISettings", "classNGUISettings.html", null ],
    [ "NGUITransformInspector", "classNGUITransformInspector.html", "classNGUITransformInspector" ],
    [ "PropertyBinding", "classPropertyBinding.html", "classPropertyBinding" ],
    [ "PropertyBindingEditor", "classPropertyBindingEditor.html", null ],
    [ "PropertyReference", "classPropertyReference.html", "classPropertyReference" ],
    [ "PropertyReferenceDrawer", "classPropertyReferenceDrawer.html", "classPropertyReferenceDrawer" ],
    [ "RealTime", "classRealTime.html", null ],
    [ "SpringPanel", "classSpringPanel.html", "classSpringPanel" ],
    [ "SpringPosition", "classSpringPosition.html", "classSpringPosition" ],
    [ "SpriteSelector", "classSpriteSelector.html", null ],
    [ "TweenAlpha", "classTweenAlpha.html", "classTweenAlpha" ],
    [ "TweenAlphaEditor", "classTweenAlphaEditor.html", null ],
    [ "TweenColor", "classTweenColor.html", "classTweenColor" ],
    [ "TweenColorEditor", "classTweenColorEditor.html", null ],
    [ "TweenFill", "classTweenFill.html", "classTweenFill" ],
    [ "TweenFOV", "classTweenFOV.html", "classTweenFOV" ],
    [ "TweenFOVEditor", "classTweenFOVEditor.html", null ],
    [ "TweenHeight", "classTweenHeight.html", "classTweenHeight" ],
    [ "TweenHeightEditor", "classTweenHeightEditor.html", null ],
    [ "TweenLetters", "classTweenLetters.html", "classTweenLetters" ],
    [ "TweenOrthoSize", "classTweenOrthoSize.html", "classTweenOrthoSize" ],
    [ "TweenOrthoSizeEditor", "classTweenOrthoSizeEditor.html", null ],
    [ "TweenPosition", "classTweenPosition.html", "classTweenPosition" ],
    [ "TweenPositionEditor", "classTweenPositionEditor.html", null ],
    [ "TweenRotation", "classTweenRotation.html", "classTweenRotation" ],
    [ "TweenRotationEditor", "classTweenRotationEditor.html", null ],
    [ "TweenScale", "classTweenScale.html", "classTweenScale" ],
    [ "TweenScaleEditor", "classTweenScaleEditor.html", null ],
    [ "TweenTransform", "classTweenTransform.html", "classTweenTransform" ],
    [ "TweenTransformEditor", "classTweenTransformEditor.html", null ],
    [ "TweenVolume", "classTweenVolume.html", "classTweenVolume" ],
    [ "TweenVolumeEditor", "classTweenVolumeEditor.html", null ],
    [ "TweenWidth", "classTweenWidth.html", "classTweenWidth" ],
    [ "TweenWidthEditor", "classTweenWidthEditor.html", null ],
    [ "TypewriterEffect", "classTypewriterEffect.html", "classTypewriterEffect" ],
    [ "TypewriterEffectEditor", "classTypewriterEffectEditor.html", null ],
    [ "UI2DSprite", "classUI2DSprite.html", "classUI2DSprite" ],
    [ "UI2DSpriteAnimation", "classUI2DSpriteAnimation.html", "classUI2DSpriteAnimation" ],
    [ "UI2DSpriteEditor", "classUI2DSpriteEditor.html", "classUI2DSpriteEditor" ],
    [ "UIAnchor", "classUIAnchor.html", "classUIAnchor" ],
    [ "UIAnchorEditor", "classUIAnchorEditor.html", null ],
    [ "UIAtlas", "classUIAtlas.html", "classUIAtlas" ],
    [ "UIAtlasInspector", "classUIAtlasInspector.html", null ],
    [ "UIAtlasMaker", "classUIAtlasMaker.html", "classUIAtlasMaker" ],
    [ "UIBasicSprite", "classUIBasicSprite.html", "classUIBasicSprite" ],
    [ "UIBasicSpriteEditor", "classUIBasicSpriteEditor.html", "classUIBasicSpriteEditor" ],
    [ "UIButton", "classUIButton.html", "classUIButton" ],
    [ "UIButtonActivate", "classUIButtonActivate.html", null ],
    [ "UIButtonColor", "classUIButtonColor.html", "classUIButtonColor" ],
    [ "UIButtonColorEditor", "classUIButtonColorEditor.html", null ],
    [ "UIButtonEditor", "classUIButtonEditor.html", null ],
    [ "UIButtonKeys", "classUIButtonKeys.html", null ],
    [ "UIButtonKeysEditor", "classUIButtonKeysEditor.html", null ],
    [ "UIButtonMessage", "classUIButtonMessage.html", null ],
    [ "UIButtonMessageEditor", "classUIButtonMessageEditor.html", null ],
    [ "UIButtonMessageExtended", "classUIButtonMessageExtended.html", null ],
    [ "UIButtonOffset", "classUIButtonOffset.html", null ],
    [ "UIButtonRotation", "classUIButtonRotation.html", null ],
    [ "UIButtonScale", "classUIButtonScale.html", null ],
    [ "UICamera", "classUICamera.html", "classUICamera" ],
    [ "UICameraEditor", "classUICameraEditor.html", null ],
    [ "UICameraTool", "classUICameraTool.html", null ],
    [ "UICenterOnChild", "classUICenterOnChild.html", "classUICenterOnChild" ],
    [ "UICenterOnClick", "classUICenterOnClick.html", null ],
    [ "UICircle", "classUICircle.html", "classUICircle" ],
    [ "UICircleEditor", "classUICircleEditor.html", "classUICircleEditor" ],
    [ "UIColorPicker", "classUIColorPicker.html", "classUIColorPicker" ],
    [ "UIColorPickerEditor", "classUIColorPickerEditor.html", null ],
    [ "UICreateNewUIWizard", "classUICreateNewUIWizard.html", null ],
    [ "UICreateWidgetWizard", "classUICreateWidgetWizard.html", null ],
    [ "UIDragCamera", "classUIDragCamera.html", "classUIDragCamera" ],
    [ "UIDragDropContainer", "classUIDragDropContainer.html", null ],
    [ "UIDragDropItem", "classUIDragDropItem.html", "classUIDragDropItem" ],
    [ "UIDragDropRoot", "classUIDragDropRoot.html", null ],
    [ "UIDraggableCamera", "classUIDraggableCamera.html", "classUIDraggableCamera" ],
    [ "UIDragObject", "classUIDragObject.html", "classUIDragObject" ],
    [ "UIDragObjectEditor", "classUIDragObjectEditor.html", null ],
    [ "UIDragResize", "classUIDragResize.html", "classUIDragResize" ],
    [ "UIDragScrollView", "classUIDragScrollView.html", "classUIDragScrollView" ],
    [ "UIDrawCall", "classUIDrawCall.html", "classUIDrawCall" ],
    [ "UIDrawCallInspector", "classUIDrawCallInspector.html", "classUIDrawCallInspector" ],
    [ "UIDrawCallViewer", "classUIDrawCallViewer.html", null ],
    [ "UIEventListener", "classUIEventListener.html", null ],
    [ "UIEventTrigger", "classUIEventTrigger.html", "classUIEventTrigger" ],
    [ "UIEventTriggerEditor", "classUIEventTriggerEditor.html", null ],
    [ "UIFont", "classUIFont.html", "classUIFont" ],
    [ "UIFontInspector", "classUIFontInspector.html", null ],
    [ "UIFontMaker", "classUIFontMaker.html", null ],
    [ "UIForwardEvents", "classUIForwardEvents.html", null ],
    [ "UIForwardEventsEditor", "classUIForwardEventsEditor.html", null ],
    [ "UIGeometry", "classUIGeometry.html", "classUIGeometry" ],
    [ "UIGrid", "classUIGrid.html", "classUIGrid" ],
    [ "UIGridEditor", "classUIGridEditor.html", null ],
    [ "UIImageButton", "classUIImageButton.html", null ],
    [ "UIImageButtonInspector", "classUIImageButtonInspector.html", null ],
    [ "UIInput", "classUIInput.html", "classUIInput" ],
    [ "UIInputEditor", "classUIInputEditor.html", null ],
    [ "UIInputOnGUI", "classUIInputOnGUI.html", null ],
    [ "UIKeyBinding", "classUIKeyBinding.html", "classUIKeyBinding" ],
    [ "UIKeyNavigation", "classUIKeyNavigation.html", "classUIKeyNavigation" ],
    [ "UIKeyNavigationEditor", "classUIKeyNavigationEditor.html", null ],
    [ "UILabel", "classUILabel.html", "classUILabel" ],
    [ "UILabelInspector", "classUILabelInspector.html", "classUILabelInspector" ],
    [ "UILabelSymbols", "classUILabelSymbols.html", "classUILabelSymbols" ],
    [ "UILocalize", "classUILocalize.html", "classUILocalize" ],
    [ "UILocalizeEditor", "classUILocalizeEditor.html", null ],
    [ "UIOrthoCamera", "classUIOrthoCamera.html", null ],
    [ "UIPanel", "classUIPanel.html", "classUIPanel" ],
    [ "UIPanelInspector", "classUIPanelInspector.html", "classUIPanelInspector" ],
    [ "UIPanelTool", "classUIPanelTool.html", null ],
    [ "UIPlayAnimation", "classUIPlayAnimation.html", "classUIPlayAnimation" ],
    [ "UIPlayAnimationEditor", "classUIPlayAnimationEditor.html", null ],
    [ "UIPlaySound", "classUIPlaySound.html", null ],
    [ "UIPlayTween", "classUIPlayTween.html", "classUIPlayTween" ],
    [ "UIPlayTweenEditor", "classUIPlayTweenEditor.html", null ],
    [ "UIPopupList", "classUIPopupList.html", "classUIPopupList" ],
    [ "UIPopupListInspector", "classUIPopupListInspector.html", null ],
    [ "UIPrefabTool", "classUIPrefabTool.html", "classUIPrefabTool" ],
    [ "UIProgressBar", "classUIProgressBar.html", "classUIProgressBar" ],
    [ "UIProgressBarEditor", "classUIProgressBarEditor.html", null ],
    [ "UIRect", "classUIRect.html", "classUIRect" ],
    [ "UIRectEditor", "classUIRectEditor.html", "classUIRectEditor" ],
    [ "UIRoot", "classUIRoot.html", "classUIRoot" ],
    [ "UIRootEditor", "classUIRootEditor.html", null ],
    [ "UISavedOption", "classUISavedOption.html", "classUISavedOption" ],
    [ "UIScrollBar", "classUIScrollBar.html", "classUIScrollBar" ],
    [ "UIScrollBarEditor", "classUIScrollBarEditor.html", null ],
    [ "UIScrollView", "classUIScrollView.html", "classUIScrollView" ],
    [ "UIScrollViewEditor", "classUIScrollViewEditor.html", null ],
    [ "UIShowControlScheme", "classUIShowControlScheme.html", null ],
    [ "UISlider", "classUISlider.html", "classUISlider" ],
    [ "UISliderEditor", "classUISliderEditor.html", null ],
    [ "UISnapshotPoint", "classUISnapshotPoint.html", null ],
    [ "UISnapshotPointEditor", "classUISnapshotPointEditor.html", null ],
    [ "UISoundVolume", "classUISoundVolume.html", null ],
    [ "UISprite", "classUISprite.html", "classUISprite" ],
    [ "UISpriteAnimation", "classUISpriteAnimation.html", "classUISpriteAnimation" ],
    [ "UISpriteAnimationInspector", "classUISpriteAnimationInspector.html", "classUISpriteAnimationInspector" ],
    [ "UISpriteCollection", "classUISpriteCollection.html", "classUISpriteCollection" ],
    [ "UISpriteCollectionEditor", "classUISpriteCollectionEditor.html", "classUISpriteCollectionEditor" ],
    [ "UISpriteData", "classUISpriteData.html", "classUISpriteData" ],
    [ "UISpriteInspector", "classUISpriteInspector.html", "classUISpriteInspector" ],
    [ "UIStretch", "classUIStretch.html", "classUIStretch" ],
    [ "UIStretchEditor", "classUIStretchEditor.html", null ],
    [ "UITable", "classUITable.html", "classUITable" ],
    [ "UITextList", "classUITextList.html", "classUITextList" ],
    [ "UITexture", "classUITexture.html", "classUITexture" ],
    [ "UITextureInspector", "classUITextureInspector.html", "classUITextureInspector" ],
    [ "UITexturePacker", "classUITexturePacker.html", "classUITexturePacker" ],
    [ "UIToggle", "classUIToggle.html", "classUIToggle" ],
    [ "UIToggledComponents", "classUIToggledComponents.html", null ],
    [ "UIToggledObjects", "classUIToggledObjects.html", null ],
    [ "UIToggleInspector", "classUIToggleInspector.html", null ],
    [ "UITooltip", "classUITooltip.html", "classUITooltip" ],
    [ "UITweener", "classUITweener.html", "classUITweener" ],
    [ "UITweenerEditor", "classUITweenerEditor.html", null ],
    [ "UIViewport", "classUIViewport.html", null ],
    [ "UIWidget", "classUIWidget.html", "classUIWidget" ],
    [ "UIWidgetContainer", "classUIWidgetContainer.html", null ],
    [ "UIWidgetContainerEditor", "classUIWidgetContainerEditor.html", "classUIWidgetContainerEditor" ],
    [ "UIWidgetInspector", "classUIWidgetInspector.html", "classUIWidgetInspector" ],
    [ "UIWrapContent", "classUIWrapContent.html", "classUIWrapContent" ],
    [ "UIWrapContentEditor", "classUIWrapContentEditor.html", null ]
];